version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
    environment:
      - REACT_APP_USER_SERVICE_URL=http://user-service:3001
      - REACT_APP_PRODUCT_SERVICE_URL=http://product-service:3002
    networks:
      - app-network

volumes:
  mongo-data:


networks:
  app-network:
    driver: bridge
