services:
  mongo:
    image: mongo
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    networks:
      - app-network
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    networks:
      - app-network
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
